---
- hosts: 127.0.0.1
  connection: local

  vars:
    http_agent: "ansible-httpget/{{ ansible_version.string }} deploy-minecraft/1.0 (compatible; +https://amaury.carrade.eu/contact)"

  tasks:
    ## import plugins list vars from /vars/games/{{ game }}/plugins.yml and register them in the variable plugins
    - name: Load plugins list vars from /vars/games/{{ game }}/plugins.yml and register them in the variable plugins
      include_vars: "vars/games/{{ game }}/plugins.yml"

    - name: Install plugins from Spigot
      include_role:
        name: install-plugin-spigot
      vars:
        plugin_name: "{{ plugin.name }}"
        spigot_id: "{{ plugin.spigot_id }}"
      loop: "{{ plugins }}"
      when: plugin.type == "spigot"
      loop_control:
        loop_var: plugin

    - name: Install plugins from direct link
      include_role:
        name: install-plugin-link
      vars:
        plugin_name: "{{ plugin.name }}"
        plugin_link: "{{ plugin.link }}"
      loop: "{{ plugins }}"
      when: plugin.type == "link"
      loop_control:
        loop_var: plugin