---
- hosts: 127.0.0.1
  connection: local
  vars:
    http_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
    support_plugin_type: ["spigot", "link"]
    failed_tasks: []
  pre_tasks:
    - name: Load vars of {{ game_type }}
      ansible.builtin.include_vars:
        dir: "vars/{{ game_type }}"
    - name: Lookup volume path
      ansible.builtin.include_tasks: "roles/common/tasks/get-volume-path-by-remoteID.yml"
      when: do_symlink is defined and do_symlink is true
  tasks:
    - name: Update plugins
      ansible.builtin.include_role:
        name: install-mc-plugin
      loop: "{{ plugins }}"
      loop_control:
        loop_var: plugin
      when: do_update is defined and do_update == "yes"
    - name: Create symbolic links
      ansible.builtin.include_role:
        name: create-symlink
      loop: "{{ plugins }}"
      loop_control:
        loop_var: plugin
      when: do_symlink is defined and do_symlink == "yes"
    - name: print failed_tasks
      ansible.builtin.debug:
        msg: "{{ failed_tasks }}"
      when: failed_tasks
